theme: jekyll-theme-cayman
title: Welcome to my portfolio website!
description: My name is Liam White. I am a graduate of Christopher Newport University with a B.S. in Computer Science. This website is where I display any personal projects I've worked on--although there is not much to show yet!
